"""
Oracle Fusion AP Interface Transformer

Converts extracted invoice data to Oracle Fusion Cloud
AP_INVOICES_INTERFACE format for direct import.
"""

import io
import json
import logging
import os
from datetime import datetime

from fdk import response

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Fusion AP Interface default values
DEFAULTS = {
    "source": "INVOICE_OCI",
    "invoice_type_lookup_code": "STANDARD",
    "payment_method_code": "CHECK",
    "terms_name": "Net 30",
    "accts_pay_code_combination_id": None,  # Set per implementation
    "org_id": os.environ.get("FUSION_ORG_ID"),
}


def transform_to_fusion_format(invoice_data: dict, invoice_id: str) -> dict:
    """
    Transform extracted invoice data to Oracle Fusion AP_INVOICES_INTERFACE format.

    Reference: Oracle Fusion Financials Cloud - Payables Interface Tables
    https://docs.oracle.com/en/cloud/saas/financials/24d/oefbf/ap-invoices-interface.html

    Args:
        invoice_data: Standardized invoice extraction
        invoice_id: Unique invoice identifier

    Returns:
        dict: Fusion AP_INVOICES_INTERFACE compatible payload
    """
    vendor = invoice_data.get("vendor", {})
    details = invoice_data.get("invoice_details", {})
    totals = invoice_data.get("totals", {})
    line_items = invoice_data.get("line_items", [])

    # Format dates for Fusion (YYYY-MM-DD)
    def format_date(date_str):
        if not date_str:
            return None
        try:
            # Handle various date formats
            for fmt in ["%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y", "%d-%m-%Y"]:
                try:
                    return datetime.strptime(date_str, fmt).strftime("%Y-%m-%d")
                except ValueError:
                    continue
            return date_str
        except Exception:
            return date_str

    # Build AP_INVOICES_INTERFACE record
    fusion_invoice = {
        # Header identification
        "InvoiceId": None,  # Generated by Fusion
        "InvoiceNum": details.get("number", invoice_id),
        "InvoiceDate": format_date(details.get("date")),
        "InvoiceReceivedDate": datetime.utcnow().strftime("%Y-%m-%d"),

        # Vendor information
        "VendorName": vendor.get("name"),
        "VendorSiteCode": vendor.get("site_code", "PRIMARY"),
        "VendorTaxRegistrationNumber": vendor.get("tax_id"),

        # Invoice amounts
        "InvoiceAmount": totals.get("total"),
        "InvoiceCurrencyCode": totals.get("currency", "USD"),
        "PaymentCurrencyCode": totals.get("currency", "USD"),

        # Payment terms
        "TermsName": details.get("payment_terms", DEFAULTS["terms_name"]),
        "TermsDate": format_date(details.get("date")),
        "PaymentMethodCode": DEFAULTS["payment_method_code"],

        # Reference information
        "PoNumber": details.get("po_number"),
        "Description": f"Invoice {details.get('number', invoice_id)} - Auto-extracted by Invoice-OCI",

        # Source tracking
        "Source": DEFAULTS["source"],
        "InvoiceTypeLookupCode": DEFAULTS["invoice_type_lookup_code"],

        # Organization
        "OrgId": DEFAULTS["org_id"],

        # Custom attributes for tracking
        "Attribute1": invoice_id,  # Original extraction ID
        "Attribute2": invoice_data.get("extraction_method", "UNKNOWN"),
        "Attribute3": str(invoice_data.get("validation", {}).get("genai_used", False)),
        "AttributeCategory": "INVOICE_OCI_EXTRACTION",

        # Line items
        "invoiceLinesCollection": []
    }

    # Build AP_INVOICE_LINES_INTERFACE records
    line_number = 1
    for item in line_items:
        # Handle both structured and raw line item formats
        if isinstance(item, dict):
            if "description" in item:
                # Structured format from GenAI
                line = {
                    "LineNumber": line_number,
                    "LineType": "ITEM",
                    "Description": item.get("description", f"Line {line_number}"),
                    "Quantity": item.get("quantity", 1),
                    "UnitPrice": item.get("unit_price", item.get("amount", 0)),
                    "Amount": item.get("amount", 0),
                    "DistributionAmount": item.get("amount", 0)
                }
            elif "cells" in item:
                # Raw table format from DU
                cells = item["cells"]
                line = {
                    "LineNumber": line_number,
                    "LineType": "ITEM",
                    "Description": cells[0] if len(cells) > 0 else f"Line {line_number}",
                    "Quantity": _parse_number(cells[1]) if len(cells) > 1 else 1,
                    "UnitPrice": _parse_number(cells[2]) if len(cells) > 2 else 0,
                    "Amount": _parse_number(cells[-1]) if len(cells) > 0 else 0
                }
                line["DistributionAmount"] = line["Amount"]
            else:
                continue
        else:
            continue

        fusion_invoice["invoiceLinesCollection"].append(line)
        line_number += 1

    # Add tax line if present
    tax_amount = totals.get("tax", 0)
    if tax_amount and tax_amount > 0:
        fusion_invoice["invoiceLinesCollection"].append({
            "LineNumber": line_number,
            "LineType": "TAX",
            "Description": "Tax",
            "Amount": tax_amount,
            "DistributionAmount": tax_amount
        })

    return fusion_invoice


def _parse_number(value) -> float:
    """Parse numeric value from various formats."""
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        # Remove currency symbols, commas, spaces
        cleaned = value.replace("$", "").replace("€", "").replace("£", "")
        cleaned = cleaned.replace(",", "").replace(" ", "").strip()
        try:
            return float(cleaned)
        except ValueError:
            return 0.0
    return 0.0


def handler(ctx, data: io.BytesIO = None):
    """
    Main function handler for Fusion transformation.

    Expects event payload with:
    - invoice_id: Unique invoice identifier
    - invoice_data: Extracted invoice data (from DU or GenAI validation)
    """
    try:
        body = json.loads(data.getvalue())

        invoice_id = body["invoice_id"]
        invoice_data = body["invoice_data"]

        logger.info(f"Transforming invoice {invoice_id} to Fusion format")

        # Transform to Fusion format
        fusion_payload = transform_to_fusion_format(invoice_data, invoice_id)

        # Validate required fields
        required_fields = ["InvoiceNum", "InvoiceDate", "VendorName", "InvoiceAmount"]
        missing_fields = [f for f in required_fields if not fusion_payload.get(f)]

        if missing_fields:
            logger.warning(f"Missing required fields: {missing_fields}")

        result = {
            "invoice_id": invoice_id,
            "status": "TRANSFORMED",
            "fusion_payload": fusion_payload,
            "line_count": len(fusion_payload.get("invoiceLinesCollection", [])),
            "total_amount": fusion_payload.get("InvoiceAmount"),
            "currency": fusion_payload.get("InvoiceCurrencyCode"),
            "missing_fields": missing_fields,
            "ready_for_import": len(missing_fields) == 0
        }

        logger.info(f"Transformation complete: {result['line_count']} lines, "
                   f"{result['total_amount']} {result['currency']}")

        return response.Response(
            ctx,
            response_data=json.dumps(result),
            headers={"Content-Type": "application/json"}
        )

    except Exception as e:
        logger.error(f"Error in Fusion transformation: {str(e)}")
        return response.Response(
            ctx,
            response_data=json.dumps({
                "error": str(e),
                "status": "TRANSFORM_FAILED",
                "invoice_id": body.get("invoice_id", "unknown")
            }),
            headers={"Content-Type": "application/json"},
            status_code=500
        )
